# Generated by Django 4.2.9 on 2024-01-27 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetailSingleJournalOfDOU',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('versao_certificada', models.URLField()),
                ('publicado_dou_data', models.DateField(null=True)),
                ('edicao_dou_data', models.CharField(null=True)),
                ('secao_dou_data', models.CharField(null=True)),
                ('orgao_dou_data', models.TextField(null=True)),
                ('title', models.CharField()),
                ('paragrafos', models.TextField(null=True)),
                ('assina', models.CharField(null=True)),
                ('cargo', models.CharField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JournalJsonArrayOfDOU',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pubName', models.CharField(null=True)),
                ('urlTitle', models.CharField(unique=True)),
                ('numberPage', models.IntegerField(null=True)),
                ('subTitulo', models.TextField(null=True)),
                ('titulo', models.TextField(null=True)),
                ('title', models.TextField(null=True)),
                ('pubDate', models.DateField(null=True)),
                ('content', models.TextField(null=True)),
                ('editionNumber', models.IntegerField(null=True)),
                ('hierarchyLevelSize', models.IntegerField(null=True)),
                ('artType', models.CharField(null=True)),
                ('pubOrder', models.CharField(null=True)),
                ('hierarchyStr', models.TextField(null=True)),
                ('hierarchyList', models.JSONField(null=True)),
            ],
        ),
    ]
